services:
  web:
    build:
      context: .
      args:
        VITE_LINKIDIN_URL: ${VITE_LINKIDIN_URL}
        VITE_GOOGLESHEET_URL: ${VITE_GOOGLESHEET_URL}
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3000:80"
    mem_limit: 400m
    restart: always